// Standart hizmet şablonları
export const MALE_SERVICES = [
  {
    name: "Saçın her türlü kesimi",
    gender: "male" as const,
    defaultPrice: 680,
    defaultDurationMinutes: 30,
    description: "Erkek saç kesimi - her türlü model",
    category: "saç",
  },
  {
    name: "Sakal kesimi",
    gender: "male" as const,
    defaultPrice: 350,
    defaultDurationMinutes: 20,
    description: "Sakal düzenleme ve kesimi",
    category: "sakal",
  },
  {
    name: "Sakal tıraşı – Saç yıkama – Fön",
    gender: "male" as const,
    defaultPrice: 790,
    defaultDurationMinutes: 40,
    description: "Komple sakal tıraşı, saç yıkama ve fön",
    category: "komple",
  },
  {
    name: "Saç – sakal kesimi",
    gender: "male" as const,
    defaultPrice: 1030,
    defaultDurationMinutes: 45,
    description: "Saç ve sakal kesimi birlikte",
    category: "komple",
  },
  {
    name: "Saçlarda tribal çizim",
    gender: "male" as const,
    defaultPrice: 400,
    defaultDurationMinutes: 20,
    description: "Saçlarda özel tribal desenler",
    category: "saç",
  },
  {
    name: "Şekilli sakal kesimi",
    gender: "male" as const,
    defaultPrice: 450,
    defaultDurationMinutes: 25,
    description: "Özel şekilli sakal düzenleme",
    category: "sakal",
  },
  {
    name: "Saçın yıkanması",
    gender: "male" as const,
    defaultPrice: 220,
    defaultDurationMinutes: 10,
    description: "Saç yıkama işlemi",
    category: "bakım",
  },
  {
    name: "Saçın fönlenmesi",
    gender: "male" as const,
    defaultPrice: 220,
    defaultDurationMinutes: 10,
    description: "Saç fönleme işlemi",
    category: "bakım",
  },
  {
    name: "Saçın friksiyonu ve kremlenmesi",
    gender: "male" as const,
    defaultPrice: 220,
    defaultDurationMinutes: 10,
    description: "Saç friksiyonu ve krem uygulaması",
    category: "bakım",
  },
  {
    name: "Saçın boyanması",
    gender: "male" as const,
    defaultPrice: 1200,
    defaultDurationMinutes: 60,
    description: "Erkek saç boyama işlemi",
    category: "saç",
  },
  {
    name: "Perma",
    gender: "male" as const,
    defaultPrice: 1500,
    defaultDurationMinutes: 90,
    description: "Erkek perma işlemi",
    category: "saç",
  },
  {
    name: "Bıyık boyama",
    gender: "male" as const,
    defaultPrice: 400,
    defaultDurationMinutes: 15,
    description: "Bıyık boyama işlemi",
    category: "sakal",
  },
  {
    name: "Sakal boyama",
    gender: "male" as const,
    defaultPrice: 500,
    defaultDurationMinutes: 20,
    description: "Sakal boyama işlemi",
    category: "sakal",
  },
  {
    name: "Cilt bakımı ve maskesi",
    gender: "male" as const,
    defaultPrice: 400,
    defaultDurationMinutes: 30,
    description: "Yüz cilt bakımı ve maske uygulaması",
    category: "bakım",
  },
  {
    name: "Ağda (yanak-kulak-ense)",
    gender: "male" as const,
    defaultPrice: 300,
    defaultDurationMinutes: 15,
    description: "Yanak, kulak ve ense ağda işlemi",
    category: "bakım",
  },
  {
    name: "Kompres yapılması",
    gender: "male" as const,
    defaultPrice: 300,
    defaultDurationMinutes: 15,
    description: "Sıcak kompres uygulaması",
    category: "bakım",
  },
  {
    name: "Masaj",
    gender: "male" as const,
    defaultPrice: 450,
    defaultDurationMinutes: 30,
    description: "Yüz ve baş masajı",
    category: "bakım",
  },
  {
    name: "Manikür ve pedikür",
    gender: "male" as const,
    defaultPrice: 700,
    defaultDurationMinutes: 45,
    description: "El ve ayak bakımı",
    category: "bakım",
  },
  {
    name: "Parafin (el ve ayak)",
    gender: "male" as const,
    defaultPrice: 400,
    defaultDurationMinutes: 25,
    description: "El ve ayak parafin uygulaması",
    category: "bakım",
  },
  {
    name: "Damat tıraşı",
    gender: "male" as const,
    defaultPrice: 2500,
    defaultDurationMinutes: 90,
    description: "Özel damat tıraşı paketi",
    category: "özel",
  },
];

export const FEMALE_SERVICES = [
  {
    name: "Modern Saç Kesimi",
    gender: "female" as const,
    defaultPrice: 1170,
    defaultDurationMinutes: 40,
    description: "Modern kadın saç kesimi",
    category: "saç",
  },
  {
    name: "Normal Saç Kesimi",
    gender: "female" as const,
    defaultPrice: 980,
    defaultDurationMinutes: 30,
    description: "Klasik kadın saç kesimi",
    category: "saç",
  },
  {
    name: "Fön",
    gender: "female" as const,
    defaultPrice: 320,
    defaultDurationMinutes: 25,
    description: "Saç fönleme işlemi",
    category: "saç",
  },
  {
    name: "Sprey",
    gender: "female" as const,
    defaultPrice: 130,
    defaultDurationMinutes: 5,
    description: "Saç spreyi uygulaması",
    category: "bakım",
  },
  {
    name: "Jöle",
    gender: "female" as const,
    defaultPrice: 130,
    defaultDurationMinutes: 5,
    description: "Saç jölesi uygulaması",
    category: "bakım",
  },
  {
    name: "Waks",
    gender: "female" as const,
    defaultPrice: 130,
    defaultDurationMinutes: 5,
    description: "Saç waksı uygulaması",
    category: "bakım",
  },
  {
    name: "Saç Yıkama ve Krem",
    gender: "female" as const,
    defaultPrice: 130,
    defaultDurationMinutes: 10,
    description: "Saç yıkama ve krem uygulaması",
    category: "bakım",
  },
  {
    name: "Saç Bakımı Yapılması",
    gender: "female" as const,
    defaultPrice: 590,
    defaultDurationMinutes: 40,
    description: "Kapsamlı saç bakım işlemi",
    category: "bakım",
  },
  {
    name: "Normal Boya (Uzun Saç)",
    gender: "female" as const,
    defaultPrice: 1830,
    defaultDurationMinutes: 80,
    description: "Uzun saç boyama işlemi",
    category: "saç",
  },
  {
    name: "Normal Boya (Kısa Saç)",
    gender: "female" as const,
    defaultPrice: 1510,
    defaultDurationMinutes: 60,
    description: "Kısa saç boyama işlemi",
    category: "saç",
  },
  {
    name: "Normal Boya (Dip Boya)",
    gender: "female" as const,
    defaultPrice: 1140,
    defaultDurationMinutes: 50,
    description: "Saç dibi boyama işlemi",
    category: "saç",
  },
  {
    name: "Rutuş Boya (Numneks)",
    gender: "female" as const,
    defaultPrice: 690,
    defaultDurationMinutes: 40,
    description: "Rutuş boya uygulaması",
    category: "saç",
  },
  {
    name: "Gelin Başı",
    gender: "female" as const,
    defaultPrice: 4690,
    defaultDurationMinutes: 120,
    description: "Özel gelin saç modeli",
    category: "özel",
  },
  {
    name: "Nişan Başı",
    gender: "female" as const,
    defaultPrice: 2750,
    defaultDurationMinutes: 90,
    description: "Özel nişan saç modeli",
    category: "özel",
  },
  {
    name: "Oreal ile Tüm Açma (Uzun Saç)",
    gender: "female" as const,
    defaultPrice: 4030,
    defaultDurationMinutes: 100,
    description: "Uzun saç için tam açma işlemi",
    category: "saç",
  },
  {
    name: "Oreal ile Tüm Açma (Kısa Saç)",
    gender: "female" as const,
    defaultPrice: 2930,
    defaultDurationMinutes: 80,
    description: "Kısa saç için tam açma işlemi",
    category: "saç",
  },
  {
    name: "Oreal ile Dip Açma",
    gender: "female" as const,
    defaultPrice: 2350,
    defaultDurationMinutes: 70,
    description: "Saç dibi açma işlemi",
    category: "saç",
  },
  {
    name: "Röfley (Uzun Saç)",
    gender: "female" as const,
    defaultPrice: 4910,
    defaultDurationMinutes: 90,
    description: "Uzun saç röfle işlemi",
    category: "saç",
  },
  {
    name: "Röfley (Kısa Saç)",
    gender: "female" as const,
    defaultPrice: 3530,
    defaultDurationMinutes: 70,
    description: "Kısa saç röfle işlemi",
    category: "saç",
  },
  {
    name: "Perma (Uzun Saç)",
    gender: "female" as const,
    defaultPrice: 3530,
    defaultDurationMinutes: 90,
    description: "Uzun saç perma işlemi",
    category: "saç",
  },
  {
    name: "Perma (Kısa Saç)",
    gender: "female" as const,
    defaultPrice: 2350,
    defaultDurationMinutes: 70,
    description: "Kısa saç perma işlemi",
    category: "saç",
  },
  {
    name: "Defrize (Uzun Saç)",
    gender: "female" as const,
    defaultPrice: 5500,
    defaultDurationMinutes: 120,
    description: "Uzun saç düzleştirme işlemi",
    category: "saç",
  },
  {
    name: "Defrize (Kısa Saç)",
    gender: "female" as const,
    defaultPrice: 3140,
    defaultDurationMinutes: 80,
    description: "Kısa saç düzleştirme işlemi",
    category: "saç",
  },
  {
    name: "Topuz",
    gender: "female" as const,
    defaultPrice: 980,
    defaultDurationMinutes: 40,
    description: "Saç topuzu yapılması",
    category: "saç",
  },
  {
    name: "Mizample",
    gender: "female" as const,
    defaultPrice: 980,
    defaultDurationMinutes: 35,
    description: "Mizample saç modeli",
    category: "saç",
  },
  {
    name: "Maşa",
    gender: "female" as const,
    defaultPrice: 980,
    defaultDurationMinutes: 35,
    description: "Maşa ile saç şekillendirme",
    category: "saç",
  },
  {
    name: "Manikür",
    gender: "female" as const,
    defaultPrice: 780,
    defaultDurationMinutes: 40,
    description: "El bakımı ve manikür",
    category: "bakım",
  },
  {
    name: "Pedikür",
    gender: "female" as const,
    defaultPrice: 980,
    defaultDurationMinutes: 45,
    description: "Ayak bakımı ve pedikür",
    category: "bakım",
  },
  {
    name: "Oje Değiştirme",
    gender: "female" as const,
    defaultPrice: 130,
    defaultDurationMinutes: 10,
    description: "Oje değiştirme işlemi",
    category: "bakım",
  },
  {
    name: "Kaş Alma",
    gender: "female" as const,
    defaultPrice: 370,
    defaultDurationMinutes: 15,
    description: "Kaş şekillendirme işlemi",
    category: "bakım",
  },
  {
    name: "Gelin ve Nişan Makyaj",
    gender: "female" as const,
    defaultPrice: 2750,
    defaultDurationMinutes: 90,
    description: "Özel gelin ve nişan makyajı",
    category: "özel",
  },
  {
    name: "Yarım Kol Ağda",
    gender: "female" as const,
    defaultPrice: 370,
    defaultDurationMinutes: 20,
    description: "Yarım kol ağda işlemi",
    category: "bakım",
  },
  {
    name: "Tam Kol Ağda",
    gender: "female" as const,
    defaultPrice: 550,
    defaultDurationMinutes: 30,
    description: "Tam kol ağda işlemi",
    category: "bakım",
  },
  {
    name: "Yarım Bacak Ağda",
    gender: "female" as const,
    defaultPrice: 580,
    defaultDurationMinutes: 30,
    description: "Yarım bacak ağda işlemi",
    category: "bakım",
  },
  {
    name: "Tüm Bacak Ağda",
    gender: "female" as const,
    defaultPrice: 660,
    defaultDurationMinutes: 45,
    description: "Tüm bacak ağda işlemi",
    category: "bakım",
  },
  {
    name: "Koltukaltı Ağda",
    gender: "female" as const,
    defaultPrice: 470,
    defaultDurationMinutes: 15,
    description: "Koltukaltı ağda işlemi",
    category: "bakım",
  },
  {
    name: "Bikini Bölgesi Ağda",
    gender: "female" as const,
    defaultPrice: 500,
    defaultDurationMinutes: 25,
    description: "Bikini bölgesi ağda işlemi",
    category: "bakım",
  },
  {
    name: "Komple Yüz Ağda",
    gender: "female" as const,
    defaultPrice: 410,
    defaultDurationMinutes: 20,
    description: "Komple yüz ağda işlemi",
    category: "bakım",
  },
  {
    name: "Tüm Vücut Ağda",
    gender: "female" as const,
    defaultPrice: 2750,
    defaultDurationMinutes: 90,
    description: "Tüm vücut ağda işlemi",
    category: "bakım",
  },
  {
    name: "Kırık Fön",
    gender: "female" as const,
    defaultPrice: 410,
    defaultDurationMinutes: 25,
    description: "Kırık fön işlemi",
    category: "saç",
  },
];

// Tüm şablonları birleştir
export const ALL_SERVICE_TEMPLATES = [
  ...MALE_SERVICES,
  ...FEMALE_SERVICES,
];